version: "3.9"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    ports:
      - 5432:5432
    container_name: postgresql_conatiner
    image: postgres
    environment:
      - POSTGRES_DB=MYDB2
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: testapp_container
    volumes:
      - D:\filles\project_programming\java\spring\GeoMapping\build\libs:/app
    ports:
      - 8089:8089
    environment:
      db-url: jdbc:postgresql://db:5432/MYDB2
      db-username: admin2
      db-password: admin2
    depends_on:
      - db
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
  grafana:
    build: './src/'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
networks:
  monitoring: