spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${db-url:jdbc:postgresql://localhost:5432/mydb}
    username: ${db-username:admin}
    password: ${db-password:admin}
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
api:
  key: 8673711a-218c-47da-ab94-af1649be48ac
server:
  port: 8089

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true